//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/_/Scripts/PlayerControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControl : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControl"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""5c67bc31-fb8d-4520-9d26-f1442d02e100"",
            ""actions"": [
                {
                    ""name"": ""Toggle Camera Lock"",
                    ""type"": ""Button"",
                    ""id"": ""9f45a641-1a46-4a08-9c88-7f68ae660acd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Focus Player"",
                    ""type"": ""Button"",
                    ""id"": ""bef8f80f-146d-4d92-8b24-04f1ae689d33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ed1b7a83-3801-4b15-88ee-340a96fceddf"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RMB Action"",
                    ""type"": ""Button"",
                    ""id"": ""30e07be3-5df4-4fc7-980d-6a826730eee3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""d9a2b096-2ca2-4783-b632-326ada10dacc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability 1"",
                    ""type"": ""Button"",
                    ""id"": ""10373d11-895b-465d-a79b-5b6fc9c015f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability 2"",
                    ""type"": ""Button"",
                    ""id"": ""c528b053-7a5b-4d5f-84a1-ea1011e4dfae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability 3"",
                    ""type"": ""Button"",
                    ""id"": ""17670e22-36ce-42b7-afc1-d81fe3b35f16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability 4"",
                    ""type"": ""Button"",
                    ""id"": ""da8d4dac-b2ec-45cf-8782-e4131cca18cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell 1"",
                    ""type"": ""Button"",
                    ""id"": ""b72ecd08-5440-4a74-b4b1-d521b0d50ca3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell 2"",
                    ""type"": ""Button"",
                    ""id"": ""ae6b798f-0d3a-463d-90a9-27400b2f511b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""48249cbc-6111-4057-a000-2210b68ce6cb"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Camera Lock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae190e5e-5e0b-45cd-8c1f-828b08f4cc19"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28f1a2fc-2ca9-4ffa-90e1-b6c6c2478660"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Focus Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a07279dc-7476-4ff4-8f82-2ebde2929cc2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RMB Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b2a5738-2119-4cb8-baee-2000a4a5f785"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""172314e0-2061-4b58-9c01-bf6ba69eaf0d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c99bbca-43c1-4430-9d73-14ea2876c1e5"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""543837fe-53ea-48d0-b193-8016c0bebfd2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3243a45-1507-4359-825e-8558f76daa23"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0d09cc7-1d10-4c78-a80f-e836250ebc9c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf9bade4-d5bb-4242-ac85-872c6309a10b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_ToggleCameraLock = m_Main.FindAction("Toggle Camera Lock", throwIfNotFound: true);
        m_Main_FocusPlayer = m_Main.FindAction("Focus Player", throwIfNotFound: true);
        m_Main_Zoom = m_Main.FindAction("Zoom", throwIfNotFound: true);
        m_Main_RMBAction = m_Main.FindAction("RMB Action", throwIfNotFound: true);
        m_Main_Stop = m_Main.FindAction("Stop", throwIfNotFound: true);
        m_Main_Ability1 = m_Main.FindAction("Ability 1", throwIfNotFound: true);
        m_Main_Ability2 = m_Main.FindAction("Ability 2", throwIfNotFound: true);
        m_Main_Ability3 = m_Main.FindAction("Ability 3", throwIfNotFound: true);
        m_Main_Ability4 = m_Main.FindAction("Ability 4", throwIfNotFound: true);
        m_Main_Spell1 = m_Main.FindAction("Spell 1", throwIfNotFound: true);
        m_Main_Spell2 = m_Main.FindAction("Spell 2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private IMainActions m_MainActionsCallbackInterface;
    private readonly InputAction m_Main_ToggleCameraLock;
    private readonly InputAction m_Main_FocusPlayer;
    private readonly InputAction m_Main_Zoom;
    private readonly InputAction m_Main_RMBAction;
    private readonly InputAction m_Main_Stop;
    private readonly InputAction m_Main_Ability1;
    private readonly InputAction m_Main_Ability2;
    private readonly InputAction m_Main_Ability3;
    private readonly InputAction m_Main_Ability4;
    private readonly InputAction m_Main_Spell1;
    private readonly InputAction m_Main_Spell2;
    public struct MainActions
    {
        private @PlayerControl m_Wrapper;
        public MainActions(@PlayerControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleCameraLock => m_Wrapper.m_Main_ToggleCameraLock;
        public InputAction @FocusPlayer => m_Wrapper.m_Main_FocusPlayer;
        public InputAction @Zoom => m_Wrapper.m_Main_Zoom;
        public InputAction @RMBAction => m_Wrapper.m_Main_RMBAction;
        public InputAction @Stop => m_Wrapper.m_Main_Stop;
        public InputAction @Ability1 => m_Wrapper.m_Main_Ability1;
        public InputAction @Ability2 => m_Wrapper.m_Main_Ability2;
        public InputAction @Ability3 => m_Wrapper.m_Main_Ability3;
        public InputAction @Ability4 => m_Wrapper.m_Main_Ability4;
        public InputAction @Spell1 => m_Wrapper.m_Main_Spell1;
        public InputAction @Spell2 => m_Wrapper.m_Main_Spell2;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void SetCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterface != null)
            {
                @ToggleCameraLock.started -= m_Wrapper.m_MainActionsCallbackInterface.OnToggleCameraLock;
                @ToggleCameraLock.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnToggleCameraLock;
                @ToggleCameraLock.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnToggleCameraLock;
                @FocusPlayer.started -= m_Wrapper.m_MainActionsCallbackInterface.OnFocusPlayer;
                @FocusPlayer.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnFocusPlayer;
                @FocusPlayer.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnFocusPlayer;
                @Zoom.started -= m_Wrapper.m_MainActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnZoom;
                @RMBAction.started -= m_Wrapper.m_MainActionsCallbackInterface.OnRMBAction;
                @RMBAction.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnRMBAction;
                @RMBAction.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnRMBAction;
                @Stop.started -= m_Wrapper.m_MainActionsCallbackInterface.OnStop;
                @Stop.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnStop;
                @Stop.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnStop;
                @Ability1.started -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility1;
                @Ability1.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility1;
                @Ability1.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility1;
                @Ability2.started -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility2;
                @Ability2.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility2;
                @Ability2.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility2;
                @Ability3.started -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility3;
                @Ability3.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility3;
                @Ability3.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility3;
                @Ability4.started -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility4;
                @Ability4.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility4;
                @Ability4.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnAbility4;
                @Spell1.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSpell1;
                @Spell1.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSpell1;
                @Spell1.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSpell1;
                @Spell2.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSpell2;
                @Spell2.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSpell2;
                @Spell2.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSpell2;
            }
            m_Wrapper.m_MainActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ToggleCameraLock.started += instance.OnToggleCameraLock;
                @ToggleCameraLock.performed += instance.OnToggleCameraLock;
                @ToggleCameraLock.canceled += instance.OnToggleCameraLock;
                @FocusPlayer.started += instance.OnFocusPlayer;
                @FocusPlayer.performed += instance.OnFocusPlayer;
                @FocusPlayer.canceled += instance.OnFocusPlayer;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @RMBAction.started += instance.OnRMBAction;
                @RMBAction.performed += instance.OnRMBAction;
                @RMBAction.canceled += instance.OnRMBAction;
                @Stop.started += instance.OnStop;
                @Stop.performed += instance.OnStop;
                @Stop.canceled += instance.OnStop;
                @Ability1.started += instance.OnAbility1;
                @Ability1.performed += instance.OnAbility1;
                @Ability1.canceled += instance.OnAbility1;
                @Ability2.started += instance.OnAbility2;
                @Ability2.performed += instance.OnAbility2;
                @Ability2.canceled += instance.OnAbility2;
                @Ability3.started += instance.OnAbility3;
                @Ability3.performed += instance.OnAbility3;
                @Ability3.canceled += instance.OnAbility3;
                @Ability4.started += instance.OnAbility4;
                @Ability4.performed += instance.OnAbility4;
                @Ability4.canceled += instance.OnAbility4;
                @Spell1.started += instance.OnSpell1;
                @Spell1.performed += instance.OnSpell1;
                @Spell1.canceled += instance.OnSpell1;
                @Spell2.started += instance.OnSpell2;
                @Spell2.performed += instance.OnSpell2;
                @Spell2.canceled += instance.OnSpell2;
            }
        }
    }
    public MainActions @Main => new MainActions(this);
    public interface IMainActions
    {
        void OnToggleCameraLock(InputAction.CallbackContext context);
        void OnFocusPlayer(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnRMBAction(InputAction.CallbackContext context);
        void OnStop(InputAction.CallbackContext context);
        void OnAbility1(InputAction.CallbackContext context);
        void OnAbility2(InputAction.CallbackContext context);
        void OnAbility3(InputAction.CallbackContext context);
        void OnAbility4(InputAction.CallbackContext context);
        void OnSpell1(InputAction.CallbackContext context);
        void OnSpell2(InputAction.CallbackContext context);
    }
}
